// affirmations.ts

export const affirmationCategories = [
  {
    id: 'super-natural-healing',
      name: 'Super Natural Healing',
      keywords: ['sadness', 'bad luck', 'change', 'spiritual', 'craving', 'urge', 'recovery'],
      affirmations: [
        { text: "I believe something wonderful is going to happen to me today.", category: 'super-natural-healing' },
        { text: "I am blessed, I am prosperous, redeemed, forgiven, healthy, whole, talented, I am creative, confident, secure, I am disciplined", category: 'super-natural-healing' },
        { text: "I am focused, prepared, qualified, motivated, valuable. I am Free, determined, equipped, empowered, anointed, accepted and approved.", category: 'super-natural-healing' },
        { text: "I am NOT average, NOT mediocre, I am a perfect child of GOD", category: 'super-natural-healing' },
             
        
    ],
  },
  {
    id: 'quit-smoking',
      name: 'Quit Smoking or Addictions',
      keywords: ['smoking', 'addiction', 'cigarette', 'drink', 'substance', 'habit', 'craving', 'urge', 'recovery', 'quit'],
      affirmations: [
        { text: "I release the urge to rely on unhealthy habits.", category: 'quit-smoking' },
        { text: "My determination to heal grows stronger each day.", category: 'quit-smoking' },
        { text: "I fill my life with activities that support my well-being.", category: 'quit-smoking' },
        { text: "I choose freedom over addiction with every decision I make.", category: 'quit-smoking' },
        { text: "My mind and body are aligned in the pursuit of health.", category: 'quit-smoking' },
        { text: "I trust the process of change and embrace it fully.", category: 'quit-smoking' },
        { text: "My inner strength is greater than any external temptation.", category: 'quit-smoking' },
        { text: "I am proud of the person I am becoming.", category: 'quit-smoking' },
        { text: "I am surrounded by support and love on my journey to recovery.", category: 'quit-smoking' },
        { text: "I replace old habits with positive, uplifting ones.", category: 'quit-smoking' },
        { text: "I am stronger than my cravings and choose a healthier path.", category: 'quit-smoking' },
        { text: "I release the hold addiction has over me.", category: 'quit-smoking' },
        { text: "Every step I take brings me closer to freedom and wellness.", category: 'quit-smoking' },
        { text: "I trust my inner strength to guide me toward recovery.", category: 'quit-smoking' },
        { text: "I deserve a life of clarity, joy, and health.", category: 'quit-smoking' },
        { text: "I forgive myself for past mistakes and focus on my growth.", category: 'quit-smoking' },
        { text: "I choose progress over perfection every day.", category: 'quit-smoking' },
        { text: "I am worthy of a life free from addiction.", category: 'quit-smoking' },
        { text: "I take pride in every small victory on my journey.", category: 'quit-smoking' },
        { text: "My commitment to healing inspires me daily.", category: 'quit-smoking' }
    ],
  },
  {
    id: 'sleep',
      name: 'Better Sleep',
      keywords: ['sleep', 'rest', 'tired', 'insomnia', 'bed', 'night', 'dream', 'relax', 'fatigue'],
      affirmations: [
        { text: "I release the stress of the day and welcome restful sleep.", category: 'sleep' },
        { text: "My mind and body relax completely as I prepare for sleep.", category: 'sleep' },
        { text: "I deserve deep, restorative sleep every night.", category: 'sleep' },
        { text: "I let go of all worries and surrender to peaceful dreams.", category: 'sleep' },
        { text: "Each night, my sleep renews and energizes me.", category: 'sleep' },
        { text: "I create a calm, comfortable space for sleep.", category: 'sleep' },
        { text: "I fall asleep easily and wake up refreshed.", category: 'sleep' },
        { text: "My body knows how to rest and heal as I sleep.", category: 'sleep' },
        { text: "I trust the process of relaxation to bring me peace.", category: 'sleep' },
        { text: "Sleep is my sanctuary, and I honor it fully.", category: 'sleep' },
        { text: "I create a peaceful environment that promotes deep rest.", category: 'sleep' },
        { text: "My body and mind work in harmony to prepare for sleep.", category: 'sleep' },
        { text: "I welcome calmness and serenity as I wind down for the night.", category: 'sleep' },
        { text: "My thoughts slow, and I feel safe as I drift into sleep.", category: 'sleep' },
        { text: "I let go of all tension and allow myself to relax completely.", category: 'sleep' },
        { text: "My sleep is deep, healing, and restorative.", category: 'sleep' },
        { text: "I honor my need for rest and prioritize it daily.", category: 'sleep' },
        { text: "Each morning, I wake up refreshed and revitalized.", category: 'sleep' },
        { text: "I trust my body's natural ability to fall asleep with ease.", category: 'sleep' },
        { text: "Sleep is my time to heal and recharge for the day ahead.", category: 'sleep' }
    ],
  },
  {
    id: 'emotional-mastery',
      name: 'Emotional Mastery',
      keywords: ['emotion', 'feeling', 'anger', 'sad', 'upset', 'mood', 'stress', 'anxiety', 'overwhelm'],
      affirmations: [
        { text: "I am the master of my emotions and respond with calmness.", category: 'emotional-mastery' },
        { text: "I allow myself to feel without being overwhelmed.", category: 'emotional-mastery' },
        { text: "Every emotion I experience teaches me something valuable.", category: 'emotional-mastery' },
        { text: "I release what no longer serves me emotionally.", category: 'emotional-mastery' },
        { text: "I choose peace over chaos in all situations.", category: 'emotional-mastery' },
        { text: "My emotional resilience grows stronger every day.", category: 'emotional-mastery' },
        { text: "I am in charge of how I react to life's challenges.", category: 'emotional-mastery' },
        { text: "I honor my emotions but do not let them define me.", category: 'emotional-mastery' },
        { text: "I attract peace and positivity into my life.", category: 'emotional-mastery' },
        { text: "I forgive myself and others, creating emotional freedom.", category: 'emotional-mastery' },
        { text: "I embrace my emotions and use them as tools for growth.", category: 'emotional-mastery' },
        { text: "I remain calm and centered in the face of challenges.", category: 'emotional-mastery' },
        { text: "I am in control of how I respond to life's ups and downs.", category: 'emotional-mastery' },
        { text: "I release negativity and welcome positive emotions into my life.", category: 'emotional-mastery' },
        { text: "My emotions are valid, and I handle them with grace.", category: 'emotional-mastery' },
        { text: "I practice mindfulness to better understand my feelings.", category: 'emotional-mastery' },
        { text: "My emotional intelligence grows stronger each day.", category: 'emotional-mastery' },
        { text: "I navigate my emotions with wisdom and self-awareness.", category: 'emotional-mastery' },
        { text: "I am free from emotional turmoil and grounded in peace.", category: 'emotional-mastery' },
        { text: "I honor my emotions without letting them control me.", category: 'emotional-mastery' }
    ],
  },
  {
    id: 'confidence',
    name: 'Confidence',
    keywords: ['confidence', 'self-esteem', 'doubt', 'fear', 'shy', 'insecure', 'worth', 'value'],
    affirmations: [
      { text: "I believe in myself and my abilities.", category: 'confidence' },
      { text: "I deserve success and happiness.", category: 'confidence' },
      { text: "I radiate confidence in all that I do.", category: 'confidence' },
      { text: "I trust myself to handle any situation with grace.", category: 'confidence' },
      { text: "I am proud of who I am becoming.", category: 'confidence' },
      { text: "My self-confidence grows with every small success.", category: 'confidence' },
      { text: "I embrace my uniqueness and celebrate my strengths.", category: 'confidence' },
      { text: "I am worthy of respect and admiration.", category: 'confidence' },
      { text: "Challenges are opportunities for me to shine.", category: 'confidence' },
      { text: "I walk through life with courage and self-assurance.", category: 'confidence' },
      { text: "I walk into every room with poise and assurance.", category: 'confidence' },
      { text: "My confidence inspires and uplifts those around me.", category: 'confidence' },
      { text: "I celebrate my achievements and embrace my potential.", category: 'confidence' },
      { text: "I am capable of achieving greatness in all areas of my life.", category: 'confidence' },
      { text: "I trust my abilities and approach challenges with courage.", category: 'confidence' },
      { text: "I attract success by believing in myself completely.", category: 'confidence' },
      { text: "I am unapologetically confident in who I am.", category: 'confidence' },
      { text: "My self-belief is unshakable, and I radiate positivity.", category: 'confidence' },
      { text: "I am deserving of all the success that comes my way.", category: 'confidence' },
      { text: "Confidence is my natural state, and I carry it effortlessly.", category: 'confidence' }
    ],
  },
{

  id: 'happiness',
  name: 'Happiness',
  keywords: ['happy', 'joy', 'depression', 'sad', 'lonely', 'smile', 'pleasure', 'contentment'],
  affirmations: [
    { text: "I choose happiness in every moment.", category: 'happiness' },
    { text: "Joy flows freely through my life.", category: 'happiness' },
    { text: "I create my own happiness and share it with others.", category: 'happiness' },
    { text: "I am grateful for the small and big joys in my life.", category: 'happiness' },
    { text: "My happiness is a reflection of my inner peace.", category: 'happiness' },
    { text: "I attract positivity and joy wherever I go.", category: 'happiness' },
    { text: "I focus on what brings me happiness and let go of negativity.", category: 'happiness' },
    { text: "I deserve to be happy and fulfilled.", category: 'happiness' },
    { text: "My heart is full of love, gratitude, and joy.", category: 'happiness' },
    { text: "Happiness is my natural state of being.", category: 'happiness' },
    { text: "I find joy in the simple pleasures of life.", category: 'happiness' },
    { text: "My heart is filled with gratitude and contentment.", category: 'happiness' },
    { text: "I spread happiness wherever I go.", category: 'happiness' },
    { text: "I allow myself to experience happiness fully and freely.", category: 'happiness' },
    { text: "My happiness shines through and brightens my world.", category: 'happiness' },
    { text: "I focus on the positive and let go of negativity.", category: 'happiness' },
    { text: "I choose to see the good in every situation.", category: 'happiness' },
    { text: "My inner happiness is not dependent on external circumstances.", category: 'happiness' },
    { text: "I am grateful for the gift of happiness in my life.", category: 'happiness' },
    { text: "I nurture my happiness by living authentically and joyfully.", category: 'happiness' }
    ]
},
{
  id: 'focus',
  name: 'Focus',
  keywords: ['focus', 'distraction', 'concentrate', 'attention', 'procrastination', 'productivity', 'mindful'],
  affirmations: [
    { text: "I concentrate easily and stay present in the moment.", category: 'focus' },
    { text: "I focus on my priorities with clarity and purpose.", category: 'focus' },
    { text: "Distractions fade away as I work toward my goals.", category: 'focus' },
    { text: "My mind is clear, calm, and productive.", category: 'focus' },
    { text: "I commit to the task at hand with full attention.", category: 'focus' },
    { text: "I honor my time by staying focused and disciplined.", category: 'focus' },
    { text: "I find joy in deep focus and purposeful work.", category: 'focus' },
    { text: "I let go of multitasking and embrace single-minded focus.", category: 'focus' },
    { text: "Each focused effort brings me closer to success.", category: 'focus' },
    { text: "I trust my ability to stay on track and achieve.", category: 'focus' },
    { text: "I direct my energy toward what truly matters.", category: 'focus' },
    { text: "My concentration improves with every focused effort I make.", category: 'focus' },
    { text: "I create mental clarity by eliminating distractions.", category: 'focus' },
    { text: "My focus is sharp, and I achieve my goals with ease.", category: 'focus' },
    { text: "I stay present and engaged in each moment.", category: 'focus' },
    { text: "I complete my tasks with precision and efficiency.", category: 'focus' },
    { text: "I maintain focus even when challenges arise.", category: 'focus' },
    { text: "My disciplined mind allows me to accomplish anything.", category: 'focus' },
    { text: "I am fully immersed in my work and achieve great results.", category: 'focus' },
    { text: "I am proud of the progress I make through focused action.", category: 'focus' }
    ]
},
{
  id: 'habits',
  name: 'Habits & Discipline',
  keywords: ['habit', 'discipline', 'routine', 'consistency', 'commitment', 'structure', 'willpower'],
  affirmations: [
    { text: "I create habits that align with my goals and values.", category: 'habits' },
    { text: "Discipline is my superpower, and I use it wisely.", category: 'habits' },
    { text: "I honor my commitments to myself and others.", category: 'habits' },
    { text: "Small, consistent actions lead to big results.", category: 'habits' },
    { text: "I stay focused and disciplined on my journey.", category: 'habits' },
    { text: "I celebrate the progress I make every day.", category: 'habits' },
    { text: "My habits reflect the person I want to become.", category: 'habits' },
    { text: "I am patient with myself as I build new routines.", category: 'habits' },
    { text: "I trust the process of growth through discipline.", category: 'habits' },
    { text: "Each day, I take intentional steps toward my best self.", category: 'habits' },
    { text: "I am committed to building habits that align with my goals.", category: 'habits' },
    { text: "My discipline is unwavering, and I honor my daily routines.", category: 'habits' },
    { text: "I celebrate the consistency I bring to my habits.", category: 'habits' },
    { text: "I make choices that reflect the person I want to be.", category: 'habits' },
    { text: "My habits are stepping stones to the life I desire.", category: 'habits' },
    { text: "Discipline empowers me to create meaningful progress.", category: 'habits' },
    { text: "I embrace small changes that lead to big transformations.", category: 'habits' },
    { text: "I remain patient and persistent as I build new habits.", category: 'habits' },
    { text: "I am proud of the structure and discipline I cultivate.", category: 'habits' },
    { text: "My habits are a reflection of my self-respect and determination.", category: 'habits' }
    ]
},
{
  id: 'money',
  name: 'Money & Finance',
  keywords: ['money', 'finance', 'wealth', 'abundance', 'prosperity', 'debt', 'income', 'financial'],
  affirmations: [
    { text: "I attract wealth and abundance effortlessly.", category: 'money' },
    { text: "Money flows to me in expected and unexpected ways.", category: 'money' },
    { text: "I use my resources wisely and with gratitude.", category: 'money' },
    { text: "I am financially secure and growing my wealth daily.", category: 'money' },
    { text: "I deserve prosperity and financial freedom.", category: 'money' },
    { text: "I am confident in my ability to manage my finances.", category: 'money' },
    { text: "I make smart decisions that align with my financial goals.", category: 'money' },
    { text: "I attract opportunities to increase my income.", category: 'money' },
    { text: "My financial success benefits me and those I love.", category: 'money' },
    { text: "Abundance is my birthright, and I claim it with joy.", category: 'money' },
    { text: "I am grateful for the financial abundance flowing into my life.", category: 'money' },
    { text: "Money is a tool that helps me create a better future.", category: 'money' },
    { text: "I attract opportunities that increase my wealth and security.", category: 'money' },
    { text: "I manage my money wisely and with confidence.", category: 'money' },
    { text: "My financial decisions reflect my values and goals.", category: 'money' },
    { text: "I deserve to live a life of financial freedom and abundance.", category: 'money' },
    { text: "My mindset around money is positive and empowering.", category: 'money' },
    { text: "I create multiple streams of income that support my dreams.", category: 'money' },
    { text: "I trust in my ability to build and sustain wealth.", category: 'money' },
    { text: "Prosperity is drawn to me, and I welcome it with gratitude.", category: 'money' }
    ]
},
{
  id: 'healing',
  name: 'Healing and Recovery',
  keywords: ['heal', 'recovery', 'pain', 'trauma', 'wellness', 'health', 'restore', 'mend'],
  affirmations: [
    { text: "My body, mind, and soul are in the process of healing.", category: 'healing' },
    { text: "I give myself time and space to recover fully.", category: 'healing' },
    { text: "Every day, I feel stronger and healthier.", category: 'healing' },
    { text: "I release pain and welcome peace into my life.", category: 'healing' },
    { text: "Healing is a journey, and I trust the process.", category: 'healing' },
    { text: "My body knows how to heal itself with care and love.", category: 'healing' },
    { text: "I surround myself with people and energy that support my recovery.", category: 'healing' },
    { text: "I forgive myself and others as part of my healing.", category: 'healing' },
    { text: "I celebrate every step of progress in my recovery.", category: 'healing' },
    { text: "I am resilient, and my healing is a gift to myself.", category: 'healing' },
    { text: "I honor my body's ability to heal and recover.", category: 'healing' },
    { text: "I am patient with myself as I navigate my healing journey.", category: 'healing' },
    { text: "My mind, body, and spirit are aligned in harmony and health.", category: 'healing' },
    { text: "I release any resistance to healing and embrace peace.", category: 'healing' },
    { text: "I trust in my body's wisdom to restore balance and vitality.", category: 'healing' },
    { text: "Each day, I take steps that support my recovery and well-being.", category: 'healing' },
    { text: "I focus on progress, not perfection, in my healing process.", category: 'healing' },
    { text: "I am surrounded by love and support during my recovery.", category: 'healing' },
    { text: "I deserve a life filled with health, happiness, and strength.", category: 'healing' },
    { text: "Healing is a journey, and I celebrate every milestone.", category: 'healing' }
    ]
},
{
  id: 'fitness',
  name: 'Fitness',
  keywords: ['fitness', 'exercise', 'workout', 'strength', 'health', 'body', 'active', 'physical'],
  affirmations: [
    { text: "I enjoy moving my body and feeling strong.", category: 'fitness' },
    { text: "Every workout brings me closer to my health goals.", category: 'fitness' },
    { text: "I am grateful for the energy and vitality my body provides.", category: 'fitness' },
    { text: "I honor my body by staying active and healthy.", category: 'fitness' },
    { text: "Fitness is a celebration of what my body can do.", category: 'fitness' },
    { text: "I grow stronger, faster, and more resilient each day.", category: 'fitness' },
    { text: "I fuel my body with nourishing foods and movement.", category: 'fitness' },
    { text: "My body is my temple, and I treat it with love.", category: 'fitness' },
    { text: "I embrace challenges as opportunities to improve my fitness.", category: 'fitness' },
    { text: "I am proud of the progress I make in my fitness journey.", category: 'fitness' },
    { text: "I am grateful for the strength and energy my body provides.", category: 'fitness' },
    { text: "My workouts energize and uplift me.", category: 'fitness' },
    { text: "I enjoy challenging my body and seeing it grow stronger.", category: 'fitness' },
    { text: "I fuel my body with movement that makes me feel alive.", category: 'fitness' },
    { text: "Fitness is a gift I give myself every day.", category: 'fitness' },
    { text: "I celebrate the progress I make on my fitness journey.", category: 'fitness' },
    { text: "I am committed to living an active, healthy lifestyle.", category: 'fitness' },
    { text: "My body is capable of amazing things, and I honor it.", category: 'fitness' },
    { text: "I prioritize fitness as a key part of my self-care routine.", category: 'fitness' },
    { text: "I am resilient, powerful, and capable of achieving my fitness goals.", category: 'fitness' }
    ]
},
{
  id: 'self-love',
  name: 'Self-Love',
  keywords: ['self-love', 'self-worth', 'self-esteem', 'acceptance', 'compassion', 'inner peace'],
  affirmations: [
    { text: "I am worthy of love, respect, and kindness.", category: 'self-love' },
    { text: "I honor and cherish myself exactly as I am.", category: 'self-love' },
    { text: "I treat myself with compassion and understanding.", category: 'self-love' },
    { text: "My flaws make me unique and beautiful.", category: 'self-love' },
    { text: "I am enough just as I am.", category: 'self-love' },
    { text: "I celebrate my achievements and forgive my mistakes.", category: 'self-love' },
    { text: "I am my own greatest ally and supporter.", category: 'self-love' },
    { text: "I radiate love and acceptance for myself and others.", category: 'self-love' },
    { text: "I deserve all the good things life has to offer.", category: 'self-love' },
    { text: "Every day, I become more confident in my own skin.", category: 'self-love' },
    { text: "I love and accept myself unconditionally.", category: 'self-love' },
    { text: "I am deserving of all the love and joy in the world.", category: 'self-love' },
    { text: "I choose to see my own beauty and worth.", category: 'self-love' },
    { text: "I am grateful for who I am becoming.", category: 'self-love' },
    { text: "I embrace all aspects of myself with love.", category: 'self-love' },
    { text: "I trust my inner wisdom and guidance.", category: 'self-love' },
    { text: "I am proud of my journey and growth.", category: 'self-love' },
    { text: "I nurture myself with loving thoughts and actions.", category: 'self-love' },
    { text: "I choose self-love over self-judgment.", category: 'self-love' },
    { text: "I am worthy of my own love and respect.", category: 'self-love' }
    ]
},
{
  id: 'relationships',
  name: 'Strengthening Relationships',
  keywords: ['relationship', 'love', 'connection', 'communication', 'trust', 'bond', 'partner', 'family', 'friend'],
  affirmations: [
    { text: "I cultivate relationships filled with love, respect, and trust.", category: 'relationships' },
    { text: "I listen and communicate with care and understanding.", category: 'relationships' },
    { text: "I am surrounded by people who uplift and inspire me.", category: 'relationships' },
    { text: "I nurture my relationships with patience and kindness.", category: 'relationships' },
    { text: "I attract healthy, meaningful connections into my life.", category: 'relationships' },
    { text: "I create a safe space for others to express themselves.", category: 'relationships' },
    { text: "I forgive and release grudges to strengthen my bonds.", category: 'relationships' },
    { text: "I value and appreciate the people in my life.", category: 'relationships' },
    { text: "I bring joy and positivity to my relationships.", category: 'relationships' },
    { text: "Every interaction is an opportunity to deepen my connections.", category: 'relationships' },
    { text: "I am worthy of loving and supportive relationships.", category: 'relationships' },
    { text: "I communicate openly and honestly with others.", category: 'relationships' },
    { text: "I attract people who respect and value me.", category: 'relationships' },
    { text: "I build strong, lasting connections with others.", category: 'relationships' },
    { text: "My relationships are based on mutual trust and respect.", category: 'relationships' },
    { text: "I am a good friend and partner to others.", category: 'relationships' },
    { text: "I choose relationships that nurture my growth.", category: 'relationships' },
    { text: "I maintain healthy boundaries in my relationships.", category: 'relationships' },
    { text: "I contribute positively to all my relationships.", category: 'relationships' },
    { text: "Love and understanding flow freely in my relationships.", category: 'relationships' }
    ]
},
{
  id: 'resilience',
  name: 'Resilience',
  keywords: ['resilient', 'strong', 'overcome', 'challenge', 'adversity', 'tough', 'bounce back', 'persevere'],
  affirmations: [
    { text: "I am stronger than any challenge that comes my way.", category: 'resilience' },
    { text: "Every setback is an opportunity to grow and learn.", category: 'resilience' },
    { text: "I bounce back with grace and determination.", category: 'resilience' },
    { text: "I have the courage to face life's uncertainties.", category: 'resilience' },
    { text: "My inner strength guides me through difficult times.", category: 'resilience' },
    { text: "I adapt and thrive in every situation I encounter.", category: 'resilience' },
    { text: "I let go of what I cannot control and focus on what I can.", category: 'resilience' },
    { text: "Challenges are stepping stones to a brighter future.", category: 'resilience' },
    { text: "I trust in my ability to overcome and succeed.", category: 'resilience' },
    { text: "Resilience is my superpower, and it grows every day.", category: 'resilience' },
    { text: "I face challenges with courage and wisdom.", category: 'resilience' },
    { text: "I am adaptable and flexible in any situation.", category: 'resilience' },
    { text: "My strength grows through every challenge.", category: 'resilience' },
    { text: "I persist even when things get difficult.", category: 'resilience' },
    { text: "I choose to rise above any obstacle.", category: 'resilience' },
    { text: "My resilience inspires others to be strong.", category: 'resilience' },
    { text: "I transform challenges into opportunities.", category: 'resilience' },
    { text: "I am unshakeable in the face of adversity.", category: 'resilience' },
    { text: "Every challenge makes me stronger and wiser.", category: 'resilience' },
    { text: "I have the power to overcome any obstacle.", category: 'resilience' }
    ]
},
{
  id: 'quality-of-life',
  name: 'Quality of Life',
  keywords: ['life', 'fulfillment', 'purpose', 'balance', 'joy', 'satisfaction', 'meaningful', 'enrichment'],
  affirmations: [
    { text: "I choose to live a life filled with joy and purpose.", category: 'quality-of-life' },
    { text: "I prioritize my well-being and happiness every day.", category: 'quality-of-life' },
    { text: "I am grateful for the abundance in my life.", category: 'quality-of-life' },
    { text: "I align my actions with what brings me fulfillment.", category: 'quality-of-life' },
    { text: "I surround myself with positivity and inspiration.", category: 'quality-of-life' },
    { text: "I balance work, rest, and play to enrich my life.", category: 'quality-of-life' },
    { text: "I embrace each moment as a gift to be cherished.", category: 'quality-of-life' },
    { text: "I create a life that reflects my values and passions.", category: 'quality-of-life' },
    { text: "I am deserving of a life full of love, peace, and prosperity.", category: 'quality-of-life' },
    { text: "Every day, I strive to improve and elevate my quality of life.", category: 'quality-of-life' },
    { text: "I create meaningful experiences in my daily life.", category: 'quality-of-life' },
    { text: "My life is filled with purpose and joy.", category: 'quality-of-life' },
    { text: "I make choices that enhance my well-being.", category: 'quality-of-life' },
    { text: "I live each day with intention and gratitude.", category: 'quality-of-life' },
    { text: "My life is a beautiful journey of growth and discovery.", category: 'quality-of-life' },
    { text: "I create a life that brings me joy and satisfaction.", category: 'quality-of-life' },
    { text: "I appreciate the simple pleasures in my daily life.", category: 'quality-of-life' },
    { text: "My life is rich with meaningful relationships and experiences.", category: 'quality-of-life' },
    { text: "I choose activities that add value to my life.", category: 'quality-of-life' },
    { text: "Every day is an opportunity to enhance my quality of life.", category: 'quality-of-life' }
    ]
},

  ];